### ISSUE TITLE
Number of cards shown is greater than the total user in users.json

### ISSUE THREAD

**Issue by Ashutosh0602** [hellofaizan/xprofile#100]
When I tested it locally there were 34 objects in an array but on page it is showing 39 cards.
It is because of passing wrong no of query in fetch url.

**Comment by hellofaizan** [comment]
Thanks for the feedback @Ashutosh0602 . It happened as recently we enabled React infinite scroll Pagination. I don't have access to my PC that's why I am not able to fix it. I was looking for someone who can contribute in fixing it. If you can solve this issue, it would be really helpful

**Comment by Ashutosh0602** [comment]
@hellofaizan I looked over it and solved, if you assign me I can make a pull request.

**Comment by hellofaizan** [comment]
Ok i am assigning it to you @Ashutosh0602

**Comment by hellofaizan** [comment]
Also if you're a designer. You can help us design a good landing page for it or you can just contribute. We are actually working on V2 of this project. Have a look around https://github.com/XProfile/xprofile

**Comment by Ashutosh0602** [comment]
I had made pr request you can check and if possible you can provide me feedback.

**Comment by hellofaizan** [comment]
Cool 👍

**Comment by hellofaizan** [comment]
I merged your pr still data card showing twice or thrice sometimes @Ashutosh0602

**Comment by Ashutosh0602** [comment]
Okay I will look over this issue now. Give me aome time.

**Comment by hellofaizan** [comment]
@Ashutosh0602 any updates??

**Comment by hellofaizan** [comment]
#111
