### ISSUE TITLE
🔥 Looking for an Active Maintainer

### ISSUE THREAD

**Issue by hellofaizan** [hellofaizan/xprofile#122]
Hey, myself Faizan, I am the project owner of XProfile. As Hectoberfest is ongoing, a lot of people are forking the repository and creating PR. I am busy with other stuff and I am not able to look into those pr and merge them.

## Requirements

- You should be good with React framework
- Active on GitHub and Discord
- Know how Github Actions work
- You should be able to help people solve the merge conflicts

Wanna be the maintainer of XProfile. Drop a message in [our Youth Icon Discord Server](https://discord.gg/vUHMxPvege)

Thank You for showing interest.

**Comment by jcgaming-official** [comment]
> Hey, myself Faizan, I am the project owner of XProfile. As Hectoberfest is ongoing, a lot of people are forking the repository and creating PR. I am busy with other stuff and I am not able to look into those pr and merge them.
> ## Requirements
> 
>     * You should be good with React framework
> 
>     * Active on GitHub and Discord
> 
>     * Know how Github Actions work
> 
>     * You should be able to help people solve the merge conflicts
> 
> 
> Wanna be the maintainer of XProfile. Drop a message in [our Youth Icon Discord Server](https://discord.gg/vUHMxPvege)
> 
> Thank You for showing interest.

I want to help but I don't have experience on React Framework :( but I'm willing to learn with it

**Comment by hellofaizan** [comment]
Awesome, are you on Discord. Join me, I will guide you, and give you maintainer role @jcgaming-official 

https://discord.gg/vUHMxPvege

**Comment by Bashamega** [comment]
If you still looking for one i am free @hellofaizan
