### ISSUE TITLE
[Bug]: Mouse icon is showing as clickable on hovering over normal text

### ISSUE THREAD

**Issue by mrinmay7875** [hellofaizan/xprofile#143]
**Describe the bug**
When user hovers over the profile description then the mouse pointer becomes palm icon which highlights that it is clickable hyperlink, But actually it is just a normal text.  Hence then mouse pointer does not need to be palm icon.

**To Reproduce**
1. Go to Home page
2. Hover over the description of a card.
3. See that the mouse pointer becomes clickable. [ Bug ]

**Expected behavior**
The mouse pointer should NOT become clickable icon.

**Screenshots**
Here is a screenshot:
<img width="1097" alt="image" src="https://github.com/hellofaizan/xprofile/assets/33797909/ca2900b2-d852-4df0-af75-6fd7950e10c8">

**Comment by Divyverma** [comment]
is this issue fixed?? or i want to contribute in this project.

**Comment by hellofaizan** [comment]
@Divyverma Its fixed, we forgot to close the issue.

**Comment by Divyverma** [comment]
Okkk
