### ISSUE TITLE
[FEAT] Add theme toogle

### ISSUE THREAD

**Issue by hellofaizan** [hellofaizan/xprofile#54]
As a user, If you want to be able to switch between light and dark themes on the website/app, so that you can choose the one that is easier on my eyes or fits your preferences.

To implement this feature, we will need to add a button or switch somewhere on the page that the user can click or tap to toggle the theme. When the user switches the theme, we will need to update the CSS styles accordingly to apply the appropriate colors, fonts, and other design elements.

In addition, we should consider storing the user's preference for the theme in a cookie or local storage, so that it persists across page reloads and sessions.

By adding this functionality, we can improve the user experience and make the website/app more accessible and customizable for our users.

**Comment by AsharMallick** [comment]
I am working on this feature

**Comment by hellofaizan** [comment]
It's Tailwind CSS btw

**Comment by AsharMallick** [comment]
Yes

**Comment by AsharMallick** [comment]
I am using context api

**Comment by hellofaizan** [comment]
Are you familiar with Shadcn-ui. Try that
