### ISSUE TITLE
[FEAT] NextJS infinite scroll pagination

### ISSUE THREAD

**Issue by hellofaizan** [hellofaizan/xprofile#60]
**🔥 Is your feature request related to a problem? Please describe.**
Yeah! It takes quite a long time to load the page when a new user visits because onLoad we try to load every single user.

**Describe the solution you'd like**
The best way to tackle this lead time down is by adding Infinite scroll pagination to the web app.

It's quite weird when a web app takes so long to just load data. That's why I want a person who would integrate infinite scroll pagination. Pagination should be added to https://x.hellofaizan.me/api/explore API, as this api loads data in random order not just like a row.

**Comment by adityyaa-10** [comment]
@hellofaizan I'd like to work on this issue.

**Comment by hellofaizan** [comment]
@adityyaa-10 Cool. I will assign you the issue

**Comment by adityyaa-10** [comment]
@hellofaizan can you explain the task in detail ?

**Comment by hellofaizan** [comment]
** Let me talk about the issue.

On page visit, it takes so long to load.
To counter that, I thought of adding pagination to the XProfile project.

** Now what is Infinite Scroll Pagination!

Firstly page should only fetch 9 user cards from the API. On scroll it should load 3 or 6 more user cards and so on till it reaches last.


*** this will load data from API as per request, that will increase page loading speed.

** API is https://x.hellofaizan.me/api/explore

**Comment by hellofaizan** [comment]
Hey @adityyaa-10 you working on this??
