### ISSUE TITLE
Cards appearing twice

### ISSUE THREAD

**Issue by DUMBANIKET** [hellofaizan/xprofile#90]
**Describe the bug**
when checking the web the cards are appearing twice at a random position

**To Reproduce**
1. Go to '[...](https://x.hellofaizan.me/)'
2. Scroll down to 
3. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/hellofaizan/xprofile/assets/111189215/77b9d4c7-8170-4652-bc50-a23946708f82)

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser Edge
 - Version NA

**Additional context**
Will try to add a pr for the patch

**Comment by hellofaizan** [comment]
Ahhh! Maybe it happened due to the explore API, as it gives data in random formats and when we use pagination with it, it throws this issue. Waiting for your pr to merge

**Comment by hellofaizan** [comment]
Any updates @DUMBANIKET

**Comment by DUMBANIKET** [comment]
> Any updates @DUMBANIKET 

Hey dude sorry for the delay, actually I wanted to add a pr but unfortunately my time is not working with me , neither I have access for my computer or laptop rn , I'm sending this message via mobile , in sometime I'll be back then I can add a pr :')
Sorry for the delay dude 😿

**Comment by hellofaizan** [comment]
Sure no issues. Take your time

**Comment by Anmol-Baranwal** [comment]
@hellofaizan 
Assign me this :)

I will raise a PR in 3 days if I'm able to solve this issue.
