### ISSUE TITLE
[💄UI] Need a good landing page for XProfile

### ISSUE THREAD

**Issue by hellofaizan** [hellofaizan/xprofile#94]
## [Repository Link](https://github.com/Youth-Icon/xprofile)

We have been continuously working on Version 2 of XProfile, where we have added a lot of features, new designs. We are looking for someone who can design a good landing page for us.

# TODO:
- Design a modern design landing page for XProfile
- [Join Discord](https://discord.gg/vUHMxPvege). The community will give  suggestions and feedbacks
- Design should be minimal and catchy

**Comment by mohak34** [comment]
@hellofaizan I think i can work on making the landing page with some guidance

**Comment by hellofaizan** [comment]
Yeah go for it @mohak34

**Comment by Prathamesh2805** [comment]
can you please assign it to me, I'm working on this.

**Comment by hellofaizan** [comment]
Have you any design inspiration first. Like first you need to design this, then you can code it
